services:
  cassandra_node1:
    image: cassandra:latest
    environment:
      - CASSANDRA_CLUSTER_NAME=mycluster
      - CASSANDRA_SEEDS=cassandra_node1,cassandra_node2
      - CASSANDRA_BROADCAST_ADDRESS=cassandra_node1
    volumes:
      - ${USERPROFILE}/cassandra/node1/data:/var/lib/cassandra/data
    networks:
      - db_cluster
    ports:
      - "9042:9042"
    healthcheck:
      test: ["CMD", "nodetool", "status"]
      interval: 30s
      timeout: 30s  
      retries: 5
      start_period: 30s

  cassandra_node2:
    image: cassandra:latest
    environment:
      - CASSANDRA_CLUSTER_NAME=mycluster
      - CASSANDRA_SEEDS=cassandra_node1,cassandra_node2
      - CASSANDRA_BROADCAST_ADDRESS=cassandra_node2
    depends_on:
      cassandra_node1:
        # condition: service_healthy
        condition: service_started
    volumes:
      - ${USERPROFILE}/cassandra/node2/data:/var/lib/cassandra/data
    networks:
      - db_cluster
    healthcheck:
      test: ["CMD", "nodetool", "status"]
      interval: 30s
      timeout: 30s 
      retries: 5
      start_period: 30s

  neo4j_db_1:
    image: neo4j:latest
    environment:
      NEO4J_AUTH: neo4j/testtest
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ${USERPROFILE}/neo4j/data1:/data
      - ${USERPROFILE}/neo4j/logs1:/logs
      - ${USERPROFILE}/neo4j/import1:/var/lib/neo4j/import
      - ${USERPROFILE}/neo4j/plugins1:/plugins
    networks:
      - db_cluster

  api_service:
    build: ./api_service
    environment:
      NEO4J_URI_1: bolt://neo4j_db_1:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: testtest
      CASSANDRA_HOST: cassandra_node1
      CASSANDRA_PORT: 9042
    depends_on:
      - neo4j_db_1
      - cassandra_node1
      - cassandra_node2
    networks:
      - db_cluster
    ports:
      - "5000:5000"
    #command: ["/bin/sh", "-c", "/usr/wait-for-it.sh neo4j_db_1:7687 --timeout=60 && /usr/wait-for-it.sh cassandra_node1:9042 --timeout=60 && uvicorn app:app --host 0.0.0.0 --port 5000"]
    command: ["/bin/sh", "-c", "/usr/wait-for-it.sh neo4j_db_1:7687 --timeout=60 && /usr/wait-for-it.sh cassandra_node1:9042 --timeout=60 && /usr/wait-for-it.sh cassandra_node2:9042 --timeout=60 && uvicorn app:app --host 0.0.0.0 --port 5000"]
networks:
  db_cluster:
    driver: bridge